### ISSUE TITLE
Nalu build warning on Power8 possibly leading to runtime issue

### ISSUE THREAD

**Issue by bschwal** [NaluCFD/Nalu#409] opened 2018-10-30 21:28 UTC
I am building Nalu on a power8 system. During the build I get many warnings like the one below:

include/master_element/MasterElementFunctions.h:96:32: warning: requested alignment 64 is larger than 16[-Wattributes]
       NALU_ALIGNED const ftype inv_detj = ftype(1.0) / det;

The build completes successfully but during the run I get this error:

terminate called after throwing an instance of 'std::invalid_argument'
  what(): /packages/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:581:

Throw number = 1

Throw test that evaluated to true: (view.extent (1) != 0 && static_cast<size_t> (view.extent (1)) <= maxColInd)

Tpetra::MultiVector<double,int,long int,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace>>::MultiVector(map,view,origView,whichVectors): view.extent(1) = 76 <= max(whichVectors) = 18446744072700340590.

Is there a flag I need to raise during the build to get the data alignment correct? Thanks in advance.

**Comment by bschwal** [comment] 2018-10-30 21:29
I am using GCC 7.2.0 to compile

**Comment by spdomin** [comment] 2018-10-30 22:24
@alanw0, do you have any insight here?

**Comment by spdomin** [comment] 2018-10-30 22:25
Also, @crtrott may have some insight..

**Comment by alanw0** [comment] 2018-10-30 22:38
I'm going to mention Robert and Shreyas (@rcknaus @sayerhs ) for expertise on the NALU_ALIGNED macro. I'm not sure that the alignment issue has anything to do with the Tpetra::MultiVector issue. This could be something in the solver stack. I would like to see more information such as a stack-trace if available.

**Comment by spdomin** [comment] 2018-10-30 23:04
@alanw0, what about these scary warnings:

include/master_element/MasterElementFunctions.h:96:32: warning: requested alignment 64 is larger than 16[-Wattributes]
NALU_ALIGNED const ftype inv_detj = ftype(1.0) / det;

I think this suggests that:

#define NALU_ALIGNED alignas(KOKKOS_MEMORY_ALIGNMENT)

is confused?

**Comment by bschwal** [comment] 2018-10-31 15:02
Getting a stack trace off our system is proving tricky. Where is the #define NALU_ALIGNED defined at? Is that something I can try to manually change?

**Comment by sayerhs** [comment] 2018-10-31 15:03
@bschwal It is defined in `include/KokkosInterface.h`, try changing it to 

```C++
#define NALU_ALIGNED alignas(alignof(double))
```

Or directly 

```C++
#define NALU_ALIGNED alignas(16)
```

**Comment by bschwal** [comment] 2018-10-31 15:30
I changed it to the latter define statement and did not get any of the warnings in my build. However, I am still receiving the same termination error.

**Comment by crtrott** [comment] 2018-10-31 15:38
I find it highly unlikely that the alignment is the cause of your tpetra issue ...

**Comment by bschwal** [comment] 2018-10-31 16:44
Just noticed I had this warning when building Trilinos with OpenMP. Still new to this codebase. 

  - Tpetra_ENABLE_CUDA is OFF, so Tpetra will assume that MPI is not CUDA aware.
NOTE: Kokkos::Serial is ON (the CMake option Kokkos_ENABLE_Serial is ON), but the corresponding Tpetra Node type is disabled.  If you want to enable instantiation and use of Kokkos::Serial in Tpetra, please also set the CMake option Tpetra_INST_SERIAL:BOOL=ON.  If you use the Kokkos::Serial Node type in Tpetra without doing this, you will get link errors!
Tpetra execution space availability (ON means available):
- Serial:  OFF
- Threads: OFF
- OpenMP:  ON
- Cuda:    OFF

**Comment by bschwal** [comment] 2018-10-31 18:53
Still having issues even after resolving this error. Any help is appreciated, thanks for the input so far.

**Comment by sayerhs** [comment] 2018-10-31 18:57
@bschwal Are you attempting to run any of the regression tests, or your own mesh/input file combination? If the latter, then I would recommend making sure of the build with regression tests first and reporting the failed regression test case.

**Comment by bschwal** [comment] 2018-10-31 19:18
I am attempting to run a mesh/input file combination that has worked on an intel system without issue.

**Comment by spdomin** [comment] 2018-10-31 20:10
I agree with @sayerhs in that running the rtest suite would be useful. I was worried about that warning, however, perhaps that was a side issue. It does still make me wonder why usage of the kokkos KOKKOS_MEMORY_ALIGNMENT variable was providing warnings. @crtrott, could you comment?

In the meantime, perhaps you could post the input file or comment on the type of physics/boundary conditions you are using?

**Comment by bschwal** [comment] 2018-10-31 20:24
Would you be so kind as to direct me to the rtest suite? I'd really appreciate. I am running the milestoneRun with 1cm_ped_35K.g.

**Comment by spdomin** [comment] 2018-11-02 16:47
To run the tests, first insure that you had the enable test in the Nalu config:

  -DENABLE_TESTS:BOOL=ON \

Then, in the /build directory, simply execute:
>ctest -j 8

the milestoneRun does not even use any of the new kokkos-based Nalu kernels?

**Comment by bschwal** [comment] 2018-11-05 14:31
ctest -j 8 results in 75/75 tests failing.

**Comment by spdomin** [comment] 2018-11-06 20:18
I will need to find a local OS that matches your setup to provide more value added. Let me look into that in the next week.

**Comment by bschwal** [comment] 2018-11-06 20:21
Thank you I appreciate your help!

**Comment by spdomin** [comment] 2019-08-14 15:46
Closing due to ticket age. We can re-open if required.

**Closed by spdomin** 2019-08-14 15:46 UTC
