### ISSUE TITLE
Generic build/test issues for Nalu

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#21] opened 2016-10-18 17:15 UTC
@NaluCFD/core, Any current build issues comment here.

**Comment by mbarone81** [comment] 2016-10-20 15:43
@spdomin, @rcknaus , I reproduced my build issue where I am attempting to build debug Nalu linked to optimized Trilinos.  In this case `make -VERBOSE=1` reveals the following compiler flag sequence: -std=c++11 -O3 -DNDEBUG -g.  So we have both -O3 and -g; this results from line 88 of CMakeLists.txt. I am not sure what *should* happen in this case.  However, when I use totalview on the resulting executable, some (not all) symbols are identified but the variable values are often mangled.

A separate question: the "-Werror" option on line 107 prevents a debug build because any warning creates an error.  Is this desired?  I always end up removing this option manually - what should I be doing?

**Comment by jhux2** [comment] 2016-10-20 17:23
@mbarone81 What exactly is the build problem you've hit?

For the record, I also hack the Nalu CMakeLists.txt file to suit my needs.  It's a valid use case to build optimized with debug symbols.  In Trilinos, you can do this with ```-D CMAKE_BUILD_TYPE:STRING=RELWITHDEBINFO```.

**Comment by mbarone81** [comment] 2016-10-20 18:27
@jhux2, the problem is that the Nalu debug executable that is generated (linked to optimized Trilinos) using unmodified cmake/config files does not seem to be compatible with totalview. My conjecture was that the appending of the Trilinos build options '-O3' to the Nalu compile flags on line 88 of CMakeLists.txt is the source of the problem.

**Comment by alanw0** [comment] 2016-10-20 19:10
@mbarone81 Regarding the debug build not working with -Werror: I've been manually removing the -Werror flag also. But I think it's highly desirable for our code to build cleanly with no warnings or errors. I think Stefan said we're waiting on a yaml fix or upgrade, hopefully that issue will resolve. In general it is harder though when our build includes code outside our control.

**Comment by mbarone81** [comment] 2016-10-20 19:29
@alanw0 Thanks for the info, good for me to have a sanity check.

**Comment by spdomin** [comment] 2016-10-20 19:36
I think that it is boost as well that has warnings that manifest in Nalu.

Agreed that we need a clean build. Sometimes, Trilinos warnings creep in as well.

**Comment by mchurchf** [comment] 2016-10-22 04:02
@mbarone81 I'm running into the same issue that the debugger I'm using, Allinea ddt, can't show what some of the variables are because of the optimization, even if I build in debug mode because it is still compiling with -O3.  Did you figure out how to turn that off?  If I go to line 88 of CMakeLists.txt, and take out the Trilinos part that gets appended on, then I don't think it is getting any flags.

**Comment by spdomin** [comment] 2016-10-22 15:52
For the time being, I think that if everyone runs with a consistent DEBUG option set in Trilinos and Nalu, all is well.

Also, if someone can look at the CMake file to clean this up, that would be great. In general, we run debug with full debug code builds. However, I suppose that allowing for mixing and matching of Nalu and Trilinos should be supported??

**Comment by mchurchf** [comment] 2016-10-24 14:27
Yes, I think that although I thought I had Trilinos built in debug mode, that didn't work properly, so Nalu was still grabbing the -03 optimize flag from the Trilinos build.

This brings up maybe a bigger picture question: for those of you who do a lot of actual Nalu development, like @spdomin and @alanw0, what tools do you use for development.  Stefan, you said you use Eclipse, but does that let you see what is going on with the variables.  I just want a smooth system for developing so that I don't have to put print statements in to see what the variables are.

**Comment by alanw0** [comment] 2016-10-24 15:07
For development I go back and forth between eclipse and vi. Eclipse provides nice navigation up and down call hierarchies, but for actual editing I like vi just because I've used it for so long.
totalview usually works well for debugging but sometimes there's no substitute for print statements.

**Comment by sayerhs** [comment] 2016-12-01 23:36
@spdomin Not sure if this is the proper place for this, if not please let me know... 

Trying to perform a debug build of Nalu (f27afd0a11342b02) on `OS X El Capitan` I get the following error with `UnitTestsKokkosViews.C` 

```
Nalu/unit_tests/UnitTestKokkosViews.C:116:8: error:
      no type named 'mt19937' in namespace 'std'
  std::mt19937 rng;
  ~~~~~^
Nalu/unit_tests/UnitTestKokkosViews.C:118:8: error:
      no template named 'uniform_real_distribution' in namespace 'std'; did you
      mean 'uniform_int_distribution'?
  std::uniform_real_distribution<double> coeff(-1.0, 1.0);
  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
       uniform_int_distribution
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2965:7: note:
      'uniform_int_distribution' declared here
class uniform_int_distribution
      ^
2 errors generated.
make[2]: *** [CMakeFiles/unittestXd.dir/unit_tests/UnitTestKokkosViews.C.o] Error 1
make[1]: *** [CMakeFiles/unittestXd.dir/all] Error 2
make: *** [all] Error 2
```

Adding `#include <random>` at the top of the file makes this error go away. Has anyone encountered this error, or did I set up something incorrectly on my macbook?

**Comment by crtrott** [comment] 2016-12-01 23:42
The include<random> should be there. This is a typical case in which some other (system) header file includes random on linux, but doesn't on mac. So you get it indirectly on the linux platforms, but on mac it fails.

**Comment by sayerhs** [comment] 2016-12-01 23:44
Thanks. I'll add the include line and submit a pull request.

**Comment by spdomin** [comment] 2016-12-02 18:15
My Mac builds have been tabled due to a Trilinos configure issue, 

https://github.com/trilinos/Trilinos/issues/882

Have you been able to config trilinos?

**Comment by crtrott** [comment] 2016-12-02 18:17
I actually never build mac.

**Comment by sayerhs** [comment] 2016-12-02 21:36
@spdomin I have not seen the issue you describe in the Trilinos bug report. I am using the `master` branch with 

```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Are you on `develop` branch by any chance? The last commit on my Trilinos pull is on Nov 9.

**Comment by mbarone81** [comment] 2017-02-16 05:07
Any ideas on what is happening here?  This is for a Trilinos build on the Cray cori machine.  I have built trilinos and 'make install' results in:

CMake Error at packages/seacas/libraries/ioss/src/main/cmake_install.cmake:56 (file):
  file RPATH_CHANGE could not write new RPATH:

    /project/projectdirs/m2593/scratch_build/install/trilinos/lib

  to the file:

    /project/projectdirs/m2593/scratch_build/install/trilinos/bin/cth_pressure_map

  No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
  packages/seacas/libraries/ioss/src/cmake_install.cmake:157 (include)
  packages/seacas/libraries/ioss/cmake_install.cmake:64 (include)
  packages/seacas/cmake_install.cmake:46 (include)
  cmake_install.cmake:85 (include)


Makefile:94: recipe for target 'install' failed

**Comment by jhux2** [comment] 2017-02-16 15:10
@mbarone81 Try adding this to your configure:

-DCMAKE_SKIP_INSTALL_RPATH=TRUE

I found this reported [here](https://github.com/trilinos/Trilinos/issues/846#issuecomment-264567505).

**Comment by mbarone81** [comment] 2017-02-16 16:56
@jhux2 Thank you, that resolved the issue.

**Comment by spdomin** [comment] 2017-02-16 18:28
Is this only for "exotic" builds? I have not seen this issue on Mac, Intel (Serrano) or gcc.

@sayerhs, I missed that error you reported on the Mac, however, recently, just added the <random? include for that reason..

**Comment by mbarone81** [comment] 2017-02-16 18:30
If exotic=Cray then I think yes.  The Trilinos issue that was tracking this was related to a build on Edison, another Cray machine.

**Comment by spdomin** [comment] 2017-03-16 17:11
My intel 17 builds are working with the HACK -restrict addition.

However, intel 16 is failing:

[ 17%] Building CXX object CMakeFiles/nalu.dir/src/element_promotion/PromotedPartHelper.C.o
[ 17%] Building CXX object CMakeFiles/nalu.dir/src/element_promotion/QuadNElementDescription.C.o
[ 18%] Building CXX object CMakeFiles/nalu.dir/src/element_promotion/QuadratureKernels.C.o
[ 18%] Building CXX object CMakeFiles/nalu.dir/src/element_promotion/QuadratureRule.C.o
[ 18%] Building CXX object CMakeFiles/nalu.dir/src/element_promotion/TensorProductQuadratureRule.C.o
/projects/netpub/nalu/NaluCFD/src/element_promotion/QuadNElementDescription.C(78): error: incomplete type is not allowed
    std::array<ordinal_type,4> edgeOrdinals = {{0, 1, 2, 3}};


In file included from /projects/netpub/nalu/NaluCFD/src/element_promotion/PromoteElement.C(24):
/projects/netpub/nalu/scratch_build/install/intel-16.0/Trilinos_stable_release/include/stk_mesh/base/HashEntityAndEntityKey.hpp(66): warning #858: type qualifier on return type is meaningless
      const size_t operator()(const stk::mesh::EntityKey& entityKey1, const stk::mesh::EntityKey& entityKey2)     const
      ^
@rcknaus, can you work with @jrood-nrel to resolve the Cmake -restrict issue in the master code base? Also, can you resolve the above warnings and error on Intel 16 (a Sky build).

**Comment by jrood-nrel** [comment] 2017-03-16 17:29
@rcknaus @spdomin  Ah my Intel build uses `-DCMAKE_CXX_FLAGS=-restrict` when I build with Spack, but I haven't added that flag to the CTest configure. Let me add this compiler-based logic into CTest and see if that will resolve it.

**Comment by rcknaus** [comment] 2017-03-16 18:46
@spdomin  I added an include for std::array.  The warning is from an STK header file, so it'll be there until STK is updated in Trilinos.

**Comment by spdomin** [comment] 2017-03-16 20:14
@alanw0, can you look a fixing the STK warning above?

**Comment by alanw0** [comment] 2017-03-16 20:26
@spdomin yes I'll take a look.

**Comment by alanw0** [comment] 2017-03-16 20:30
@spdomin it has been fixed in sierra's version of stk, hopefully will be updated into Trilinos soon. I have seen email traffic from Brent working on doing the update.

**Comment by spdomin** [comment] 2017-04-21 15:15
On Intel, I see the following warning:

In file included from /projects/netpub/nalu/NaluCFDSerrano/src/AssembleElemSolverAlgorithm.C(33):
/projects/netpub/nalu/NaluCFDSerrano/include/ScratchViews.h(63): warning #858: type qualifier on return type is meaningless
    inline const int total_bytes() const { return num_bytes_required; }

**Comment by sayerhs** [comment] 2017-04-21 15:16
Intel is complaining about `const` for a temporary copy that is returned. Was `const int&` intended?

**Comment by alanw0** [comment] 2017-04-21 15:19
I think it just needs to not say const on the return type. Const does nothing for a return-by-value.

Alan


On Apr 21, 2017, at 9:16 AM, Shreyas Ananthan <notifications@github.com<mailto:notifications@github.com>> wrote:


Intel is complaining about const for a temporary copy that is returned. Was const int& intended?

-

**Comment by jrood-nrel** [comment] 2017-04-22 02:18
Is this why my intel built binary segfaults now? Because I am baffled at whether or not I am doing anything wrong.

```

**Comment by spdomin** [comment] 2017-06-03 13:24
The nightly unit tests are failing on Peregrine:

[  FAILED  ] MasterElementSideNodeOrdinals.pyr_side_node_ordinals_are_same_as_stk

This suggests that the update of Trilinos is not taking place.

**Comment by spdomin** [comment] 2017-10-30 14:33
Anyone see this error:

http://my.cdash.org/viewBuildError.php?buildid=1314533 ?

**Comment by alanw0** [comment] 2017-10-30 14:44
Yes I noticed that on the dashboard. Git blame indicates that line hasn't been changed for a while:
6a89b0d2 (Shreyas Ananthan 2017-08-04 08:39:43 -0700
I don't know exactly what's going on there. I can look into it unless @sayerhs is looking at it.

**Comment by sayerhs** [comment] 2017-10-30 14:47
I am at the airport right now and cannot look at it right away. Looks like a change in Kokkos removed/changed the behavior of KOKKOS_ALIGN

**Comment by alanw0** [comment] 2017-10-30 14:48
@sayerhs no problem, I'll take a look at it. I agree it must be due to a change in Kokkos because that code has been in nalu for a while.

**Comment by sayerhs** [comment] 2017-10-30 14:52
@alanw0 Try including `Kokkos_Macros.hpp` in addition to `Kokkos_Core.hpp`?

**Comment by alanw0** [comment] 2017-10-30 16:00
@spdomin @sayerhs I've made an attempt at fixing this. I included Kokkos_Macros.hpp as Shreyas suggested, and also slightly altered the code. It looked like KOKKOS_ALIGN should come before the variable name instead of after. It built/ran fine on my system, we'll see what the dashboard says.

**Comment by spdomin** [comment] 2017-10-30 16:35
@mhoemmen offered to review this error: http://my.cdash.org/viewBuildError.php?buildid=1314533

**Comment by mhoemmen** [comment] 2017-10-30 20:17
`KOKKOS_ALIGN` is completely gone from the version of Kokkos snapshotted into Trilinos:develop.

**Comment by mhoemmen** [comment] 2017-10-30 20:22
It looks like users are not meant to use this macro any more.  The new macro name is `KOKKOS_IMPL_ALIGN_PTR`.  You could try using that for now, but `IMPL` in the name strongly suggests that Kokkos makes no promise of backwards compatibility for this macro.

**Comment by mhoemmen** [comment] 2017-10-30 20:26
I've filed this as a Kokkos issue: https://github.com/kokkos/kokkos/issues/1203

**Comment by mhoemmen** [comment] 2017-10-30 20:29
This Kokkos issue (closed) may be relevant: https://github.com/kokkos/kokkos/issues/1004

**Comment by mhoemmen** [comment] 2017-10-30 20:29
btw, Trilinos pull requests document Kokkos develop -> master promotions: https://github.com/trilinos/Trilinos/pull/1916

**Comment by mhoemmen** [comment] 2017-10-30 20:31
Yup, the fix for that Kokkos issue renamed `KOKKOS_ALIGN_PTR` to `KOKKOS_IMPL_ALIGN_PTR`:

https://github.com/kokkos/kokkos/pull/1115

**Comment by alanw0** [comment] 2017-10-30 20:37
It appears as though apps weren't intended to use the KOKKOS_ALIGN macro, and I suspect it wouldn't be a great idea to use KOKKOS_IMPL_ALIGN_PTR either. Perhaps we should just use __attribute__((aligned(64)) raw ourselves. (Actually, define our own macro that does that.)

**Comment by mhoemmen** [comment] 2017-10-30 21:08
@alanw0 Be sure to protect use of double underlines with backquotes, else GitHub turns them into bold text: `__attribute__((aligned(64))`

**Comment by mhoemmen** [comment] 2017-10-30 21:09
It looks like `KOKKOS_MEMORY_ALIGNMENT` is still legit.  You could replace 64 in the above bit of code with this macro.

**Comment by alanw0** [comment] 2017-10-30 21:17
Compiler doesn't like KOKKOS_MEMORY_ALIGNMENT. Is there a chance that's a new macro that's not in our version of kokkos yet?

**Comment by mhoemmen** [comment] 2017-10-30 22:14
@alanw0 It is in Trilinos develop, not in master yet apparently.

**Comment by spdomin** [comment] 2017-10-31 23:25
Most developers build against develop. However, my Trilinos version that most developers use has not been updated. I can do this later this week.

**Comment by jrood-nrel** [comment] 2017-11-09 22:24
Currently clang has problems with:
```
Nalu/src/master_element/Quad92DCVFEM.C:584:48: error: invalid suffix 'd' on floating constant
  const DoubleType realmin = 2.2250738585072014d-308;
                                               ^
```

**Comment by spdomin** [comment] 2017-11-10 16:34
@alanw0, I think that there is a std::percision that can be used, right? Is that suitable with DoubleType?

**Comment by alanw0** [comment] 2017-11-10 16:38
@spdomin in fact, now that you mention it, I see that we are initializing realmin in 14 different places in the master-elem code. It should definitely be consolidated into 1 place, and it would probably be better to use something from numeric_limits... I'll look into that.

**Comment by spdomin** [comment] 2017-11-10 16:39
right.. I meant numerical limits:)

**Closed** 2019-06-11 17:18 UTC
Labels: question
